jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

spring:
  datasource:
    url: jdbc:h2:mem:ing
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}